language: python

python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"

before_install:
  - sudo apt-get update
  - sudo apt-get -y install libblas-dev liblapack-dev gfortran

install:
  - pip install -e .

script: run_stratify_noddi -h

env:
  - ANTSPATH=/PATH/TO/ANTS FSLDIR=/PATH/TO/FSL
