#!/usr/bin/env python

import os
import json
import amico
import glob
import argparse as ap
import numpy as np
import nibabel as nib
import dipy.reconst.dti as dti
from dipy.reconst.dti import fractional_anisotropy, mean_diffusivity, radial_diffusivity, axial_diffusivity,mode
import dipy.denoise.noise_estimate as ne
import dipy.io as io
import dipy.core.gradients as cg

from stratify_noddi.functions import antsLinearRegCmd, antsNonLinearRegCmd, antsApplyTransformCmd, runCmd_log, antsBetCmd, check_dwi_files, generate_qc_tsv

DESCRIPTION = "Multi-shell DWI and NODDI Processing script for IMAGEN FU3 and STRATIFY"

def getArgumentParser(ap = ap.ArgumentParser(description = DESCRIPTION)):
	ap.add_argument("-s", "--subjid",
		nargs = 1,
		help = "Subject ID",
		metavar = ('str'),
		required = True)
	ap.add_argument("-dwi", "--dwipath",
		nargs = "+",
		help = "-dwi {bval} {bvec} {4D_dwiimage} [optional {json}]. E.g., -dwi path/to/sub-TEST.*",
		type = str,
		metavar = ('str'),
		required = True)
	edc_method = ap.add_mutually_exclusive_group(required = True)
	edc_method.add_argument("-pab0", "--pab0path",
		nargs = "+",
		help = "-padwi {4D_b0image} [{bval} {bvec} optional {json}]. E.g., -dwi path/to/sub-TEST.*",
		type = str,
		metavar = ('str'))
	edc_method.add_argument("-t1", "--t1path",
		nargs = 1,
		help = "-t1 {T1w_image}",
		type = str,
		metavar = ('str'))
	ap.add_argument("-trot", "--totalreadouttime",
		nargs = 1,
		help = "-trot {total readout time} (default: %(default)s)",
		type = str,
		metavar = ('str'),
		default = ['0.0876336'])
	ap.add_argument("--defaultnumopposingb0",
		nargs = 1,
		help = "--defaultnumopposingb0. Sets the number of pa b0s to extract from the start if pa vector/bval files are missing (default: %(default)s)",
		type = int,
		metavar = ('int'),
		default = [3])
	ap.add_argument("-rr", "--runrestore",
		help = "Use RESTORE for robust tensor fitting",
		action = "store_true")
	ap.add_argument("-nt", "--numthreads", 
		nargs=1,
		default=[2],
		type = int,
		help="Multithreading (default: %(default)s). Only partially implemented")
	return ap

#Naming template
#{subject}_dti.mif	
#{subject}_dti_denoised.mif	
#{subject}_dti_noise.mif	
#{subject}_dti_denoised_degibbsed.mif	
#{subject}_dti_denoised_degibbsed_preprocessed.mif	
#eddy_qc
#{subject}_dti_denoised_degibbsed_preprocessed_biascorrected.mif	
#{subject}_dti_denoised_degibbsed_preprocessed_biascorrected_mask.nii.gz	
#{subject}_dti_denoised_degibbsed_preprocessed_biascorrected_tensor.nii.gz	
#{subject}_dti_denoised_degibbsed_preprocessed_biascorrected_fa.nii.gz	
#{subject}_dti_denoised_degibbsed_preprocessed_biascorrected_adc.nii.gz	
#{subject}_dti_denoised_degibbsed_preprocessed_biascorrected_ad.nii.gz	
#{subject}_dti_denoised_degibbsed_preprocessed_biascorrected_rd.nii.gz	
#{subject}_dti_denoised_degibbsed_preprocessed_biascorrected_L1.nii.gz	
#{subject}_dti_denoised_degibbsed_preprocessed_biascorrected_L2.nii.gz	
#{subject}_dti_denoised_degibbsed_preprocessed_biascorrected_L3.nii.gz	
#{subject}_dti_denoised_degibbsed_preprocessed_biascorrected_V1.nii.gz	
#{subject}_dti_denoised_degibbsed_preprocessed_biascorrected_V2.nii.gz	
#{subject}_dti_denoised_degibbsed_preprocessed_biascorrected_V3.nii.gz	


def run(opts):

	subject = opts.subjid[0]
	BVAL_path = check_dwi_files(opts.dwipath, ".bval")
	BVEC_path = check_dwi_files(opts.dwipath, ".bvec")
	DWI_path = check_dwi_files(opts.dwipath, ".nii.gz")
	JSON_path = check_dwi_files(dwi_opts = opts.dwipath, extension = '.json')
	numthreads = opts.numthreads[0]
	TotalReadoutTime = str(opts.totalreadouttime[0])
	N_PA_B0 = int(opts.defaultnumopposingb0[0])
	
	# list of intermediate files for cleanup
	intermediate_files = []

	if JSON_path is not None:
		with open(JSON_path) as dwi_json_file:
			dwi_json = json.load(dwi_json_file)
		TotalReadoutTime = str(dwi_json["TotalReadoutTime"])
		print("Total Readout Time from %s is: %s" % (JSON_path, TotalReadoutTime))

	if opts.t1path:
		T1w_path = opts.t1path[0]
		T1w_path = os.path.abspath(T1w_path)
	if opts.pab0path:
		pa_BVAL_path = check_dwi_files(opts.pab0path, ".bval")
		pa_BVEC_path = check_dwi_files(opts.pab0path, ".bvec")
		pa_DWI_path = check_dwi_files(opts.pab0path, ".nii.gz")
		pa_JSON_path = check_dwi_files(opts.pab0path, ".json")
	DWI_path = os.path.abspath(DWI_path)
	BVEC_path = os.path.abspath(BVEC_path)
	BVAL_path = os.path.abspath(BVAL_path)

	runCmd_log("mkdir -p %s" % subject)
	os.chdir(subject)
	pdir_basename = os.getcwd() + "/"

	# copy and rename dwi
	runCmd_log("mkdir -p processed")
	
	# declare names
	DWI = pdir_basename + "processed/%s_dti-AP.nii.gz" % subject
	BVAL = pdir_basename + "processed/%s_dti-AP.bval" % subject
	BVEC = pdir_basename + "processed/%s_dti-AP.bvec" % subject
	MIF = pdir_basename + "processed/%s_dti-AP.mif" % subject

	# copy nifti
	runCmd_log("cp %s %s" % (DWI_path, DWI))
	runCmd_log("cp %s %s" % (BVAL_path, BVAL))
	runCmd_log("cp %s %s" % (BVEC_path, BVEC))
	runCmd_log("mrconvert -fslgrad %s %s %s %s" % (BVEC_path, BVAL_path, DWI_path, MIF)

	if opts.t1path:
		T1W = pdir_basename + "processed/%s_T1w.nii.gz" % subject
		runCmd_log("cp %s %s" % (T1w_path, T1W))
	if opts.pab0path:
		# declare names
		MIF_PA = pdir_basename + "processed/%s_dti-PA.mif" % subject
		B0_PA = pdir_basename + "processed/%s_b0-PA.mif" % subject
		B0_AP = pdir_basename + "processed/%s_b0-AP.mif" % subject
		paBVEC = pdir_basename + "processed/%s_dti-PA.bvec" % subject
		paBVAL = pdir_basename + "processed/%s_dti-PA.bval" % subject
		#this will be cut
		paDWI = pdir_basename + "processed/%s_dti-PA.nii.gz" % subject
		if pa_BVAL_path is not None:
			runCmd_log("cp %s %s" % (pa_BVAL_path, paBVAL))
		else:
			print("processed/%s_dti-PA.bval not found. Creating is a dummy bval [0 0 0 2000]")
			os.system("echo 0 0 0 2000 > processed/%s_dti-PA.bval" % subject)
		if pa_BVEC_path is not None:
			runCmd_log("cp %s %s" % (pa_BVEC_path, paBVEC))
		else:
			print("processed/%s_dti-PA.bvec not found. Creating it as a zero'd bvec file" % subject)
			np.savetxt("processed/%s_dti-PA.bvec" % subject, np.zeros((3,4)), fmt="%d")
		
		# convert to mif
		runCmd_log("mrconvert -fslgrad %s %s %s %s" % (paBVEC, paBVAL, pa_DWI_path, MIF_PA))
		runCmd_log("mrconvert %s -coord 3 0,1,2 %s" % (MIF_PA, B0_PA))

		AP_B0_bval = np.genfromtxt(BVAL, delimiter=" ")
		AP_B0_bval_round = np.round(AP_B0_bval,-3).astype(int)
		AP_B0_index = AP_B0_bval_round==0
		AP_B0_indices = np.squeeze(np.argwhere(AP_B0_index == True))
		runCmd_log("mrconvert %s -coord 3 %s %s" % (MIF, ",".join(AP_B0_indices.astype(str)), B0_AP))
		num_AP_B0 = len(AP_B0_bval_round[AP_B0_index])

		# legacy
		runCmd_log("cp %s %s" % (pa_DWI_path, paDWI))


	# declare names
	DWI_DN = pdir_basename + "processed/%s_dti-AP_denoised.mif" % subject
	intermediate_files.append(DWI_DN)
	DWI_DN_NOISE = pdir_basename + "processed/%s_noise.mif" % subject
	intermediate_files.append(DWI_DN_NOISE)
	DWI_DN_DG = pdir_basename + "processed/%s_dti-AP_denoised_degibbsed.mif" % subject
	intermediate_files.append(DWI_DN_DG)
	
	# denoise. 
	runCmd_log("dwidenoise %s %s -noise %s" % (DWI, DWI_DN, DWI_DN_NOISE))
	# degibbs.
	runCmd_log("mrdegibbs %s %s" % (DWI_DN, DWI_DN_DG))
	# make mask (useful for checking) ... could be used in dwifslpreproc
	runCmd_log("dwi2mask %s processed/%s_dti-AP_mask.nii.gz " % (MIF, subject))

	# round the bval for NODDI/indexing
	DWI_DN_EDDY_BVAL_ROUNDED = pdir_basename + "processed/%s_dti-AP_denoised_degibbsed_preprocessed_rounded.bval" % subject
	bval = np.genfromtxt(BVAL, delimiter=' ', dtype=int)
	rounded_bval = np.around(bval, decimals=-3)
	# output round bval which is later used for amico
	np.savetxt(DWI_DN_EDDY_BVAL_ROUNDED, rounded_bval, delimiter='', newline=' ', fmt='%i')

	if opts.t1path:
		# EDDY
		# declare names
		DWI_DN_EDDY = pdir_basename + "processed/%s_dti-AP_denoised_degibbsed_preprocessed.nii.gz" % subject
		DWI_DN_EDDY_BVEC = pdir_basename + "processed/%s_dti-AP_denoised_degibbsed_preprocessed.bvec" % subject
		DWI_DN_EDDY_BVAL = pdir_basename + "processed/%s_dti-AP_denoised_degibbsed_preprocessed.bval" % subject
	
		# Unwarping using T1w image 
		runCmd_log("dwifslpreproc -fslgrad %s %s -rpe_none -pe_dir ap -readout_time %s -export_grad_fsl %s %s %s %s" % (BVEC, BVAL,
										TotalReadoutTime,
										DWI_DN_EDDY_BVEC, DWI_DN_EDDY_BVAL,
										DWI_DN_DG, DWI_DN_EDDY))

		assert os.path.exists(DWI_DN_EDDY), "DWI preprocessing did not finish. Is GCC loaded?"

		# N4 bias field correction for T1w image
		T1W_N4 = pdir_basename + "processed/%s_T1w_bfc.nii.gz" % subject
		runCmd_log("N4BiasFieldCorrection -d 3 -i %s -o %s" % (T1W, T1W_N4))

		# ANTS brain extraction; antsbet does do a N4bfc, but this way makes sure that the structural template is unbiased for registration. Unlikely to have much of an effect w/ or w/out N4...
		runCmd_log(antsBetCmd(numthreads = numthreads, input_image = T1W_N4, output_image_brain = "processed/%s_T1w_bfc_" % subject))

		# declare names
		T1w_brain = pdir_basename + "processed/%s_T1w_bfc_BrainExtractionBrain.nii.gz" % subject


		# get the mean B0 images
		img = nib.load(DWI_DN_EDDY)
		img_data = img.get_fdata()
		bzero_data = img_data[:,:,:,rounded_bval==0]

		# declare names
		DWI_DN_EDDY_B0_MEAN = pdir_basename + "processed/%s_dti-AP_denoised_degibbsed_preprocessed_b0_mean.nii.gz" % subject
		DWI_DN_EDDY_B0_MEAN_BRAIN = pdir_basename + "processed/%s_dti-AP_denoised_degibbsed_preprocessed_b0_mean_brain.nii.gz" % subject

		nib.save(nib.nifti1.Nifti1Image(bzero_data.mean(3), header=img.header, affine=img.affine), DWI_DN_EDDY_B0_MEAN)
		runCmd_log("bet %s %s -f .2" % (DWI_DN_EDDY_B0_MEAN, DWI_DN_EDDY_B0_MEAN_BRAIN))

		# linear registration of T1w_brain to B0_mean_brain
		ref = DWI_DN_EDDY_B0_MEAN_BRAIN
		mov = T1w_brain
		out = 'processed/lin_T1w_to_b0.nii.gz'
		runCmd_log(antsLinearRegCmd(numthreads = numthreads,
											reference  = ref,
											mov = mov,
											out_basename = out,
											outdir = None,
											use_float=False))

		# non linear registration of B0_mean_brain to lin_T1w_to_b0.nii.gz
		ref = 'processed/lin_T1w_to_b0.nii.gz'
		mov = DWI_DN_EDDY_B0_MEAN_BRAIN
		out = 'processed/b0_to_linT1.nii.gz'
		runCmd_log(antsNonLinearRegCmd(numthreads = numthreads,
												reference = ref,
												mov = mov,
												out_basename = out,
												outdir = None,
												use_float = False))

		# apply transformation to DWI data
		# declare names
		DWI_DN_EDDY_DC = pdir_basename + "processed/%s_dti-AP_denoised_degibbsed_preprocessed_biascorrected.nii.gz" % subject
		warps = ["processed/b0_to_linT1.nii.gz_0Warp.nii.gz"]
		runCmd_log(antsApplyTransformCmd(reference = ref,
													mov = DWI_DN_EDDY,
													warps = warps,
													outname = DWI_DN_EDDY_DC,
													inverse = False, multipleimages = True))

		# subject_dti-AP_ecc_dc_mask. Note: I'm using the linear transformed T1w mask to avoid fitting outside the unwarping area
		# declare names
		DWI_DN_EDDY_DC_MASK = pdir_basename + "processed/%s_dti-AP_denoised_degibbsed_preprocessed_biascorrected_mask.nii.gz" % subject
		DWI_DN_EDDY_DC_ERO1 = pdir_basename + "processed/%s_dti-AP_denoised_degibbsed_preprocessed_biascorrected_mask_ero1.nii.gz" % subject
		runCmd_log("fslmaths processed/lin_T1w_to_b0.nii.gz -bin %s" % DWI_DN_EDDY_DC_MASK)
		runCmd_log("fslmaths processed/lin_T1w_to_b0.nii.gz -bin -ero %s" % DWI_DN_EDDY_DC_ERO1)

		runCmd_log("mkdir QC")
		runCmd_log("fslsplit %s QC/" % DWI_DN_EDDY_DC)
		runCmd_log("slicesdir -p processed/lin_T1w_to_b0.nii.gz QC/*")
		runCmd_log("rm -r QC")
		runCmd_log("mv slicesdir processed/QC_unwarped_dwi")


	if opts.pab0path:

		#declare names
		B0_ALL = "processed/%s_b0-all.mif" % subject
		B0_AP_GRAD = "processed/%s_b0-AP.grad" % subject
		B0_PA_GRAD = "processed/%s_b0-PA.grad" % subject
		DWI_DN_EDDY_DC = pdir_basename + "processed/%s_dti-AP_denoised_degibbsed_preprocessed.mif" % subject
		DWI_DN_EDDY_DC_BC = pdir_basename + "processed/%s_dti-AP_denoised_degibbsed_preprocessed_biascorrected.nii.gz" % subject
		DWI_DN_EDDY_DC_BC_MASK = pdir_basename + "processed/%s_dti-AP_denoised_degibbsed_preprocessed_biascorrected_mask.nii.gz" % subject
		DWI_DN_EDDY_DC_BC_TENSOR = pdir_basename + "processed/%s_dti-AP_denoised_degibbsed_preprocessed_biascorrected_tensor.nii.gz" % subject
		DWI_DN_EDDY_BVEC = pdir_basename + "processed/%s_dti-AP_denoised_degibbsed_preprocessed_biascorrected.bvec" % subject
		DWI_DN_EDDY_BVAL = pdir_basename + "processed/%s_dti-AP_denoised_degibbsed_preprocessed_biascorrected.bval" % subject

		# make the opposing B0 file, make sure everything is zeroed for EDDY, json import is necessary for -rpe_header option.
		np.savetxt(B0_AP_GRAD, np.zeros((8,4)), fmt="%d")
		np.savetxt(B0_PA_GRAD, np.zeros((3,4)), fmt="%d")
		runCmd_log("mrconvert -force -grad %s -json_import %s %s %s" % (B0_AP_GRAD, JSON_path, B0_AP, B0_AP))
		runCmd_log("mrconvert -force -grad %s -json_import %s %s %s" % (B0_PA_GRAD, pa_JSON_path, B0_PA, B0_PA))
		runCmd_log("mrcat %s %s %s -axis 3" % (B0_AP, B0_PA, B0_ALL))

		# add the gradient_table back to DWI. Why is this necessary?
		runCmd_log("mrconvert -force -fslgrad %s %s -json_import %s %s %s" % (BVEC_path, BVAL_path, JSON_path, DWI_DN_DG, DWI_DN_DG))

		# Unwarping / EDDY
		runCmd_log("mkdir -p processed/eddy_qc")
		runCmd_log("mkdir -p processed/eddytmp")
		runCmd_log("""dwifslpreproc -nthreads %d \
						-eddyqc_text processed/eddytmp -scratch processed/eddytmp -eddy_options ' --cnr_maps --repol ' \
						-rpe_header -nocleanup \
						-se_epi %s -align_seepi \
						-export_grad_fsl %s %s \
						%s %s""" % (numthreads, B0_ALL,
										DWI_DN_EDDY_BVEC, DWI_DN_EDDY_BVAL,
										DWI_DN_DG, DWI_DN_EDDY_DC))
		runCmd_log("dwibiascorrect ants %s %s" % (DWI_DN_EDDY_DC, DWI_DN_EDDY_DC_BC))
		
		# I'm going to use the B0 mask for metric fitting instead becasue dwi2mask cuts too much into grey matter. However, I'll still calculate the MRTRix's mask.
		# declare names
		DWI_B0_AVERAGE = pdir_basename + "processed/%s-b0_average.nii.gz" % subject
		DWI_B0_AVERAGE_MASK = pdir_basename + "processed/%s-b0_average_brain_mask.nii.gz" % subject
		DWI_B0_AVERAGE_BRAIN = pdir_basename + "processed/%s-b0_average_brain.nii.gz" % subject
		# create average unwarped B0 and create mask
		img = nib.load(DWI_DN_EDDY_DC_BC)
		b0_average = np.mean(img.get_fdata()[:,:,:,rounded_bval == 0],-1)
		nib.save(nib.Nifti1Image(b0_average, img.affine), DWI_B0_AVERAGE)
		runCmd_log("bet %s %s -f .2 -m" % (DWI_B0_AVERAGE, DWI_B0_AVERAGE_BRAIN))
		
		# MRTrix's dwi mask
		runCmd_log("dwi2mask -fslgrad %s %s %s %s" % (DWI_DN_EDDY_BVEC, DWI_DN_EDDY_BVAL, DWI_DN_EDDY_DC_BC, DWI_DN_EDDY_DC_BC_MASK))
		runCmd_log("dwi2tensor -mask %s -fslgrad %s %s %s %s" % (DWI_B0_AVERAGE_MASK, DWI_DN_EDDY_BVEC, DWI_DN_EDDY_BVAL, DWI_DN_EDDY_DC_BC, DWI_DN_EDDY_DC_BC_TENSOR))
		for m in ['adc', 'fa', 'ad', 'rd']:
			runCmd_log("tensor2metric -%s processed/%s_dti-AP_denoised_degibbsed_preprocessed_biascorrected_%s.nii.gz -mask %s %s" % (m, subject, m, DWI_B0_AVERAGE_MASK, DWI_DN_EDDY_DC_BC_TENSOR))

		# this seems to copy vector three times... check.
		for i in [1, 2, 3]:
			runCmd_log("tensor2metric -value processed/%s_dti-AP_denoised_degibbsed_preprocessed_biascorrected_L%d.nii.gz -num %d -mask %s %s" % (subject, i, i, DWI_B0_AVERAGE_MASK, DWI_DN_EDDY_DC_BC_TENSOR))
			runCmd_log("tensor2metric -vector processed/%s_dti-AP_denoised_degibbsed_preprocessed_biascorrected_V%d.nii.gz -num %d -mask %s %s" % (subject, i, i, DWI_B0_AVERAGE_MASK, DWI_DN_EDDY_DC_BC_TENSOR))

		# calculate the inverted MD image
		runCmd_log("fslmaths processed/%s_dti-AP_denoised_degibbsed_preprocessed_biascorrected_adc.nii.gz -thr 0.0001 -recip processed/%s_dti-AP_denoised_degibbsed_preprocessed_biascorrected_invadc.nii.gz" % (subject, subject))




	# option to run restore. I'm going to use the B0 mask because dwi2mask cuts out too much grey matter.
	if opts.runrestore:
		# adapted from https://github.com/imagen2/imagen_processing/blob/master/fsl_dti/restore.py
		# dipy page: http://nipy.org/dipy/examples_built/restore_dti.html
		# load dti data
		img = nib.load(DWI_DN_EDDY_DC_BC)
		# is this really necessary? why not just used the masked data?
		dataraw = img.get_fdata()
		maskdata = nib.load(DWI_B0_AVERAGE_MASK).get_fdata()
		data = img.get_fdata()
		data[maskdata!=1] = 0
		bvals, bvecs = io.read_bvals_bvecs(DWI_DN_EDDY_BVAL, DWI_DN_EDDY_BVEC)
		# load bvec and bvals
		gtab = cg.gradient_table(bvals, bvecs)
		# noise estimation from the b=0
		sigma = ne.estimate_sigma(dataraw[:,:,:,rounded_bval==0])
		sigmamean = np.mean(sigma)
		# tensor computation using restore
		tenmodel = dti.TensorModel(gtab,fit_method='RESTORE', sigma=sigmamean)
		tenfit = tenmodel.fit(data)

		FA = fractional_anisotropy(tenfit.evals)
		MD = mean_diffusivity(tenfit.evals)
		AD = axial_diffusivity(tenfit.evals)
		RD = radial_diffusivity(tenfit.evals)
		MO = mode(tenfit.evecs)

		# change output names to use '-' instead of '_' so there isn't an issues with the QC
		tenfit.evals[np.isnan(tenfit.evals)] = 0
		evals1_img = nib.Nifti1Image(tenfit.evals[:,:,:,0].astype(np.float32), img.get_affine())
		nib.save(evals1_img, "processed/%s_dti-AP_denoised_degibbsed_preprocessed_biascorrected_restore-L1.nii.gz" % subject)
		evals2_img = nib.Nifti1Image(tenfit.evals[:,:,:,1].astype(np.float32), img.get_affine())
		nib.save(evals2_img, "processed/%s_dti-AP_denoised_degibbsed_preprocessed_biascorrected_restore-L2.nii.gz" % subject)
		evals3_img = nib.Nifti1Image(tenfit.evals[:,:,:,2].astype(np.float32), img.get_affine())
		nib.save(evals3_img, "processed/%s_dti-AP_denoised_degibbsed_preprocessed_biascorrected_restore-L3.nii.gz" % subject)

		tenfit.evecs[np.isnan(tenfit.evecs)] = 0
		evecs_img1 = nib.Nifti1Image(tenfit.evecs[:,:,:,:,0].astype(np.float32), img.get_affine())
		nib.save(evecs_img1, "processed/%s_dti-AP_denoised_degibbsed_preprocessed_biascorrected_restore-V1.nii.gz" % subject)
		evecs_img2 = nib.Nifti1Image(tenfit.evecs[:,:,:,:,1].astype(np.float32), img.get_affine())
		nib.save(evecs_img2, "processed/%s_dti-AP_denoised_degibbsed_preprocessed_biascorrected_restore-V2.nii.gz" % subject)
		evecs_img3 = nib.Nifti1Image(tenfit.evecs[:,:,:,:,2].astype(np.float32), img.get_affine())
		nib.save(evecs_img3, "processed/%s_dti-AP_denoised_degibbsed_preprocessed_biascorrected_restore-V3.nii.gz" % subject)

		FA[np.isnan(FA)] = 0
		FA[maskdata!=1] = 0
		fa_img = nib.Nifti1Image(FA.astype(np.float32), img.get_affine())
		nib.save(fa_img, "processed/%s_dti-AP_denoised_degibbsed_preprocessed_biascorrected_restore-fa.nii.gz" % subject)

		MD[np.isnan(MD)] = 0
		MD[maskdata!=1] = 0
		md_img = nib.Nifti1Image(MD.astype(np.float32), img.get_affine())
		nib.save(md_img, "processed/%s_dti-AP_denoised_degibbsed_preprocessed_biascorrected_restore-adc.nii.gz" % subject)

		RD[np.isnan(RD)] = 0
		RD[maskdata!=1] = 0
		rd_img = nib.Nifti1Image(RD.astype(np.float32), img.get_affine())
		nib.save(rd_img, "processed/%s_dti-AP_denoised_degibbsed_preprocessed_biascorrected_restore-rd.nii.gz" % subject)

		MO[np.isnan(MO)] = 0
		MO[maskdata!=1] = 0
		mo_img = nib.Nifti1Image(MO.astype(np.float32), img.get_affine())
		nib.save(mo_img, "processed/%s_dti-AP_denoised_degibbsed_preprocessed_biascorrected_restore-mo.nii.gz" % subject)

		runCmd_log("fslmaths processed/%s_dti-AP_denoised_degibbsed_preprocessed_biascorrected_restore-adc.nii.gz -thr 0.0001 -recip processed/%s_dti-AP_denoised_degibbsed_preprocessed_biascorrected_restore-invadc.nii.gz" % (subject, subject))

	# NODDI
	noddi_dir = "processed/noddi"
	runCmd_log("mkdir -p " + noddi_dir)
	os.chdir(noddi_dir)

	runCmd_log("zcat %s > subject4d.nii" % (DWI_DN_EDDY_DC_BC))
	runCmd_log("zcat %s > mask.nii" % (DWI_B0_AVERAGE_MASK))

	amico.core.setup()
	scheme_name = ("amico.scheme")
	amico.util.fsl2scheme(DWI_DN_EDDY_BVAL_ROUNDED,
								DWI_DN_EDDY_BVEC,
								schemeFilename = scheme_name)
	ae = amico.Evaluation("","")
	ae.load_data(dwi_filename = "subject4d.nii",
					scheme_filename = "amico.scheme",
					mask_filename = "mask.nii",
					b0_thr = 0)
	ae.set_model("NODDI")
#	ae.set_config('doDebiasSignal', True)
#	ae.set_config('DWI-SNR', 30.0)
	ae.generate_kernels(regenerate = True)
	ae.load_kernels()
	ae.fit()
	ae.save_results()
	for metric in ['ICVF','OD', 'ISOVF']:
		runCmd_log("cp AMICO/NODDI/FIT_%s.nii.gz ../%s_dti-AP_denoised_degibbsed_preprocessed_biascorrected_brain_%s.nii.gz" % (metric, subject, metric))
	runCmd_log("rm -rf mask.nii subject4d.nii kernels")
	
	# There are spikes in the OD/ICVF histogram images, but that seems to be okay? -> https://github.com/daducci/AMICO/issues/8
	
	# SNR of B0 images. Is this a good estimate of noise?
	img = nib.load(DWI_DN_EDDY_DC_BC)
	dataraw = img.get_fdata()
	maskdata = nib.load(DWI_B0_AVERAGE_MASK).get_fdata()
	masked = dataraw[maskdata==1]
	mean = np.mean(masked[:,rounded_bval==0],1)
	std = np.std(masked[:,rounded_bval==0],1)
	snr_b0 = mean / std
	snr_img = np.zeros_like(maskdata)
	snr_img[maskdata==1] = snr_b0
	nib.save(nib.Nifti1Image(snr_img, img.affine), "processed/%s-b0_denoised_degibbsed_preprocessed_biascorrected_snr.nii.gz" % (subject))

	# output QC logs and histograms
	DWI_METRICS = np.sort(glob.glob("processed/%s_dti-AP_denoised_degibbsed_preprocessed_biascorrected_*.nii.gz" % (subject)))
	generate_qc_tsv(images = DWI_METRICS,
						outname = 'processed/%s_dti-AP_denoised_degibbsed_preprocessed_biascorrected_brain_tf.log' % subject,
						sep = "\t",
						generate_histogram = True)

if __name__ == "__main__":
	parser = getArgumentParser()
	opts = parser.parse_args()
	run(opts)

